### ISSUE TITLE
Failing tests due to pickle error

### ISSUE THREAD

**Issue by dobey** [ubports/click#7]
The following test failures are happening in CI:

```
======================================================================

ERROR: test_gc (click_package.tests.test_database.TestClickSingleDB)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/build/varlibjenkinsworkspaceclickxenialrmcacheclickubportsgbpbcadsc/click_package/tests/test_database.py", line 360, in test_gc

    enter()

  File "/build/varlibjenkinsworkspaceclickxenialrmcacheclickubportsgbpbcadsc/click_package/tests/gimock.py", line 480, in helper

    exctype = pickle.load(reader)

EOFError: Ran out of input



======================================================================

ERROR: test_gc_fixes_old_user_registrations (click_package.tests.test_database.TestClickSingleDB)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/build/varlibjenkinsworkspaceclickxenialrmcacheclickubportsgbpbcadsc/click_package/tests/test_database.py", line 430, in test_gc_fixes_old_user_registrations

    enter()

  File "/build/varlibjenkinsworkspaceclickxenialrmcacheclickubportsgbpbcadsc/click_package/tests/gimock.py", line 480, in helper

    exctype = pickle.load(reader)

EOFError: Ran out of input



======================================================================

ERROR: test_maybe_remove_not_running (click_package.tests.test_database.TestClickSingleDB)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/build/varlibjenkinsworkspaceclickxenialrmcacheclickubportsgbpbcadsc/click_package/tests/test_database.py", line 341, in test_maybe_remove_not_running

    enter()

  File "/build/varlibjenkinsworkspaceclickxenialrmcacheclickubportsgbpbcadsc/click_package/tests/gimock.py", line 480, in helper

    exctype = pickle.load(reader)

EOFError: Ran out of input
```

**Comment by dobey** [comment]
It seems this may no longer be an issue, as I've made a branch to re-enable these tests on focal and the issue did not recur. I will close this as that change is on gitlab.
